apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    # any outside object trying to get access to redis pod
    # this is port the service is exposing
    - port:  6379
    # targetPort = the port on the target pod we are providing access to
      targetPort: 6379